import { Client as VerifierClient, networks } from './noir_verifier_bindings/src';
import { rpc } from '@stellar/stellar-sdk';

const RPC_URL = 'https://soroban-testnet.stellar.org';
const VERIFIER_CONTRACT_ID = 'CDH3DFQDGSTX4CCG7L7J4NGRCLMNZGOK5VLIBSYAWBLO2ODNANOZLRC2';

/**
 * SHA-256 da VK do circuito zk-porrinha v2 (circuits/zk-porrinha/vk.bin, 1779 bytes).
 * Qualquer outra VK — isto é, qualquer outro circuito — será rejeitada pelo contrato.
 */
export const VK_HASH = Buffer.from(
  'ac147cd32a5681d6d29487088e5250b616e9ec4f42ea095eb07a68b89640a6b5',
  'hex'
);

/**
 * Initialize the Noir verifier client
 */
export function getVerifierClient(publicKey?: string) {
  const rpcServer = new rpc.Server(RPC_URL);
  
  return new VerifierClient({
    ...networks.testnet,
    rpcUrl: RPC_URL,
    networkPassphrase: networks.testnet.networkPassphrase,
    contractId: VERIFIER_CONTRACT_ID,
    publicKey,
  });
}

/**
 * Verify a Noir proof on-chain using the Stellar verifier contract.
 * Passes the VK hash para que o contrato valide que a prova é deste circuito.
 * @param proof - The proof bytes generated by Noir/Barretenberg
 * @param publicInputs - 7 × 32-byte inputs: h1, h2, parity1, parity2, exact1, exact2, total_sum
 * @param publicKey - The user's public key (for signing)
 * @returns true if proof is valid, false otherwise
 */
export async function verifyProofOnChain(
  proof: Uint8Array,
  publicInputs: Uint8Array[],
  publicKey: string
): Promise<boolean> {
  try {
    const client = getVerifierClient(publicKey);
    
    const proofBuffer = Buffer.from(proof);
    const publicInputsBuffers = publicInputs.map(input => Buffer.from(input));
    
    console.log('🔍 Verifying proof on-chain...');
    console.log('Proof size:', proof.length, 'bytes');
    console.log('Public inputs:', publicInputsBuffers.length);
    console.log('VK hash:', VK_HASH.toString('hex'));
    
    // Camada 1: VK hash vincula a prova a este circuito específico
    // Camada 2: BN254 pairing check criptográfico real
    const tx = await client.verify({
      proof: proofBuffer,
      public_inputs: publicInputsBuffers,
      vk_hash: VK_HASH,
    });
    
    const result = await tx.simulate();
    
    console.log('✅ Verification result:', result.result);
    
    return result.result || false;
  } catch (error) {
    console.error('❌ Verification failed:', error);
    return false;
  }
}

/**
 * Register a circuit hash with the verifier contract
 * This allows the contract to validate which circuits are trusted
 */
export async function registerCircuit(
  circuitHash: Uint8Array,
  name: string,
  version: number,
  publicKey: string
): Promise<boolean> {
  try {
    const client = getVerifierClient(publicKey);
    
    const circuitHashBuffer = Buffer.from(circuitHash);
    
    console.log('📝 Registering circuit:', name, 'v' + version);
    
    const tx = await client.register_circuit({
      circuit_hash: circuitHashBuffer,
      name: name.substring(0, 9), // Symbol max length is 9
      version,
    });
    
    const result = await tx.signAndSend();
    
    console.log('✅ Circuit registered:', result);
    
    return true;
  } catch (error) {
    console.error('❌ Circuit registration failed:', error);
    return false;
  }
}

/**
 * Get circuit info from the verifier contract
 */
export async function getCircuitInfo(
  circuitHash: Uint8Array,
  publicKey?: string
): Promise<{ circuit_hash: Buffer; name: string; version: number } | null> {
  try {
    const client = getVerifierClient(publicKey);
    
    const circuitHashBuffer = Buffer.from(circuitHash);
    
    const tx = await client.get_circuit({
      circuit_hash: circuitHashBuffer,
    });
    
    const result = await tx.simulate();
    
    return result.result || null;
  } catch (error) {
    console.error('❌ Failed to get circuit info:', error);
    return null;
  }
}

/**
 * Alias para verifyProofOnChain com VK hash explícito.
 * Mantido por retrocompatibilidade — usa sempre o VK_HASH do circuito atual.
 * @deprecated Use verifyProofOnChain que já inclui o VK_HASH automaticamente.
 */
export async function verifyProofWithCircuit(
  proof: Uint8Array,
  publicInputs: Uint8Array[],
  _circuitHash: Uint8Array,
  publicKey: string
): Promise<boolean> {
  // Ignora o circuitHash passado e usa o VK_HASH embarcado no verifier.ts.
  // O contrato v5 valida internamente via SHA-256 da VK.
  return verifyProofOnChain(proof, publicInputs, publicKey);
}
